In [1]:
import numpy as np
numpy_arr=np.array([2,3,5,7,11])
print(numpy_arr)
add=numpy_arr+2
print(add)
multi=numpy_arr*3
print(multi)
div=numpy_arr/2
print(div)

[ 2  3  5  7 11]
[ 4  5  7  9 13]
[ 6  9 15 21 33]
[1.  1.5 2.5 3.5 5.5]


In [2]:
arr=np.array([1,2,3,6,4,5])
arr_rev=arr[::-1]
print(arr_rev)

[5 4 6 3 2 1]


In [3]:
def most_frequent(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_count = np.max(counts)
    most_frequent_value = values[np.argmax(counts)]
    indices = np.where(arr == most_frequent_value)[0]
    return most_frequent_value, indices

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

mf_x, indices_x = most_frequent(x)
mf_y, indices_y = most_frequent(y)

print(f'Most frequent value in x: {mf_x}, Indices: {indices_x}')
print(f'Most frequent value in y: {mf_y}, Indices: {indices_y}')

Most frequent value in x: 1, Indices: [0 5 7 8 9]
Most frequent value in y: 1, Indices: [0 1 2]


In [4]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print('Q3a:', arr[0, 1])  # Output: 20
print('Q3b:', arr[2, 0])  # Output: 70

Q3a: 20
Q3b: 70


In [5]:
akshit=np.linspace(10, 100, 25)
print(akshit)
print(f'Array: {akshit}')
print(f'Dimensions: {akshit.ndim}')
print(f'Shape: {akshit.shape}')
print(f'Total elements: {akshit.size}')
print(f'Data type: {akshit.dtype}')
print(f'Total bytes: {akshit.nbytes}')
print('Transpose of the array :',akshit.reshape(len(akshit),1))
print('Transpose of the array :',akshit.T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose of the array : [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose of the array : [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [6]:
ucs420_akshit = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("Mean:", np.mean(ucs420_akshit))
print("Median:", np.median(ucs420_akshit))
print("Max:", np.max(ucs420_akshit))
print("Min:", np.min(ucs420_akshit))
print("Unique Elements:", np.unique(ucs420_akshit))
reshaped_ucs420_akshit = ucs420_akshit.reshape(4, 3)
print("Reshaped:\n", reshaped_ucs420_akshit)
resized_ucs420_akshit = np.resize(ucs420_akshit, (2, 3))
print("Resized:\n", resized_ucs420_akshit)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized:
 [[10 20 30]
 [40 50 60]]
